### ISSUE TITLE
AWS Fargate is replacing environment variables (AWS_*)

### ISSUE THREAD

**Issue by 4183r** [exaco/laravel-octane-dockerfile#10]
The issue comes when we're running the docker image in ECS. 
it's replacing AWS_DEFAULT_REGION from `eu-central-1` to `eu-west-2`

![image](https://user-images.githubusercontent.com/39749258/155079066-15eeecca-f2c2-4641-b676-a8e906becbd8.png)
----

With FPM it loads the ENV normally 
![image](https://user-images.githubusercontent.com/39749258/155077931-d637f950-c8f2-45b1-b8a2-bd03f8a79e5b.png)

our .env file
![image](https://user-images.githubusercontent.com/39749258/155079401-7373cdbf-2eca-43a3-bfb6-9cdf6ee717e8.png)

So we're trying to access the S3 bucket which is hosted in a `eu-central-1` region. and we're running ECS in `eu-west-2`

**Comment by smortexa** [comment]
Sorry. I have no idea. Maybe you should open this issue on the Octane repository.
