### ISSUE TITLE
[Doubt] Why 2 composer install?

### ISSUE THREAD

**Issue by ProtocolNebula** [exaco/laravel-octane-dockerfile#101]
Hi,

I want to improve the build process of the Dockerfile, and I have a doubt, why composer install is run twice (with different parameters)?

File: `Swoole.Alpine.Dockerfile`

```dockerfile
RUN composer install \
    --no-dev \
    --no-interaction \
    --no-autoloader \
    --no-ansi \
    --no-scripts \
    --audit
```

```dockerfile
RUN composer install \
    --classmap-authoritative \
    --no-interaction \
    --no-ansi \
    --no-dev \
    && composer clear-cache
```

I don't know what all parameters do (I have to investigate about them), but with just one run should be enough, so... There is a specific reason for it?

Thanks for the clarification.

**Comment by smortexa** [comment]
This approach defers the creation of the Composer autoloader file, optimizing the use of Docker's image cache and improving build efficiency.

Running `composer du` unexpectedly installs development packages (at least as of the time of writing).

**Comment by ProtocolNebula** [comment]
Thanks for the response.

I didn’t though it affected to the dockers cache.
