### ISSUE TITLE
Octane Cache Driver Not Supported

### ISSUE THREAD

**Issue by anabeto93** [exaco/laravel-octane-dockerfile#21]
This is more of a cry for help than a bug. I have already asked a question on stackoverflow hoping to get help from someone.

[https://stackoverflow.com/questions/72547132/laravel-octane-cache-driver-not-supported](https://stackoverflow.com/questions/72547132/laravel-octane-cache-driver-not-supported)

For some reason, when a call is made to `Cache::store('octane')` when serving an http request, an error is thrown. But if I manually access it from `php artisan tinker` console, it does not throw an error.

**Comment by michabbb** [comment]
so what has been the reason ????
