### ISSUE TITLE
Permission denied on laravel.log during start

### ISSUE THREAD

**Issue by ludgerey** [exaco/laravel-octane-dockerfile#27]
I have a fresh laravel installation and added the files from this repo according to the instructions. The app won't start when running `docker run`.

```
2022-09-13 08:03:55,959 INFO spawned: 'octane_00' with pid 69

In StreamHandler.php line 146:

  The stream or file "/var/www/html/storage/logs/laravel.log" could not be op
  ened in append mode: Failed to open stream: Permission denied
  The exception occurred while attempting to log: The stream or file "/var/ww
  w/html/storage/logs/laravel.log" could not be opened in append mode: Failed
   to open stream: Permission denied
  The exception occurred while attempting to log: There are no commands defin
  ed in the "octane" namespace.
  Context: {"exception":{}}
  Context: {"exception":{}}
```

How to fix this? Is this a bug?

**Comment by ludgerey** [comment]
Nevermind, had to add octane via composer before and install it according to the laravel docs. Maybe add this requirement to the docs?

**Comment by meeftah** [comment]
could you explain more? I face some problem

**Comment by ludgerey** [comment]
@meeftah I think I described it, the best I can above already. If you have another issue, I guess it's best when you create a new issue and describe in detail what your problem is.
