### ISSUE TITLE
Problem running container

### ISSUE THREAD

**Issue by tiagodevweb** [exaco/laravel-octane-dockerfile#3]
Complaining about Class "Facade\Ignition\IgnitionServiceProvider" not found when running the container, I realized that this is a require-dev dependency and that --no-scripts doesn't enable @php artisan package:discover --ansi if you move for require dependencies, do you have any solution?

**Comment by smortexa** [comment]
If you need this package, I think you should try to run `composer install` command without any flag or exactly without `--no-dev` flag.

**Comment by tiagodevweb** [comment]
Thanks for the feedback

**Comment by smortexa** [comment]
@tiagodevweb Please remove `composer.lock` before building the image. Maybe solves the problem.

**Comment by tiagodevweb** [comment]
Actually the problem was with the bootstrap cache
