### ISSUE TITLE
./deployment/octane/entrypoint.sh: no such file or directory: unknown

### ISSUE THREAD

**Issue by Dasinfomedia2** [exaco/laravel-octane-dockerfile#4]
```
 => naming to docker.io/library/accounts_lumen                                                                  0.0s
Starting accounts ... error

ERROR: for accounts  Cannot start service lumen: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "./deployment/octane/entrypoint.sh": stat ./deployment/octane/entrypoint.sh: no such file or directory: unknown

ERROR: for lumen  Cannot start service lumen: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "./deployment/octane/entrypoint.sh": stat ./deployment/octane/entrypoint.sh: no such file or directory: unknown
ERROR: Encountered errors while bringing up the project.
```
The file exists in the docker folder still facing any issue
My Folder structure is as below.
`accounts\docker\deployment\octane\entrypoint.sh`

The below step works. If I rename entrypoint.sh file then it shows file not found in this step.
`=> CACHED [stage-1 22/23] RUN chmod +x ./deployment/octane/entrypoint.sh `

**Comment by Dasinfomedia2** [comment]
`=> CACHED [stage-1 22/23] RUN chmod +x ./deployment/octane/entrypoint.sh `
this step works. If rename file then it shows file not found in this step.

**Comment by smortexa** [comment]
@Dasinfomedia2 Please ensure that `deployment` directory is in your Laravel base path. Otherwise be aware that `docker` directory is added to `.dockerignore` file, so it will be ignored during building image. You are free to remove it from `.dockerignore`.

**Comment by Dasinfomedia2** [comment]
@smortexa 
I have modified dockerfile as below
```
# ENTRYPOINT ["./deployment/octane/entrypoint.sh"]
CMD ["/usr/bin/supervisord","-c","/etc/supervisor/conf.d/supervisord.conf"]
```
 I commented entrypoint where it was generating error and moved the needed code in docerfile itself and its working.

Anu suggestion or improvments ?

Thanks for reply. :

**Comment by smortexa** [comment]
Just be sure your files are in the correct places. I can not reproduce this problem, so if it works, It's OK.
