### ISSUE TITLE
Scheduler issues - can't run overlapping tasks

### ISSUE THREAD

**Issue by varemel** [exaco/laravel-octane-dockerfile#49]
Thanks for your work.

Faced 2 issues regarding Laravel scheduler:
1. Can't run more than 1 job simultaneously. Reason is lack of `-overlapping`flag in supercronic start command (https://github.com/aptible/supercronic#duplicate-jobs).

Suggest to add this flag in supervisord.app.conf
```
[program:scheduler]
...
command=supercronic -overlapping /etc/supercronic/laravel
...
```

2. Need to clear jobs mutexes in case of container restart.

Suggest to add to supervisord.app.conf one time process with `autorestart=false`

```
[program:clear-scheduler-cache]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/artisan schedule:clear-cache
user=%(ENV_NON_ROOT_USER)s
autostart=%(ENV_APP_WITH_SCHEDULER)s
autorestart=false
stdout_logfile=/var/www/html/scheduler.log
```

**Comment by smortexa** [comment]
Thanks for your suggestions, and I'm happy to say I've implemented them.
