### ISSUE TITLE
Unable to locate binary

### ISSUE THREAD

**Issue by DanjBethel** [exaco/laravel-octane-dockerfile#66]
I keep getting the message "Unable to locate Frankenphp binary."

**Comment by tommmoe** [comment]
> I keep getting the message "Unable to locate Frankenphp binary."

Make sure you don't have a composer file and run it with the specified command line

**Comment by DanjBethel** [comment]
In the dockerfile, I can see the line where the Frankenphp binary should be copied from the "server" block into the root directory but I don't actually see the binary. Not sure if that has anything to do with the composer file.

**Comment by tommmoe** [comment]
> In the dockerfile, I can see the line where the Frankenphp binary should be copied from the "server" block into the root directory but I don't actually see the binary. Not sure if that has anything to do with the composer file.
> […](#)
> On 15 Mar 2024 at 8:41 PM -0400, tommmoe ***@***.***>, wrote: > I keep getting the message "Unable to locate Frankenphp binary." Make sure you don't have a composer file and run it with the specified command line — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

well can you see if it's pulled the server down in your docker log? from a vanilla docker install, this repo does work
