### ISSUE TITLE
Can't change `max_execution_time` value

### ISSUE THREAD

**Issue by Cemoche** [exaco/laravel-octane-dockerfile#7]
Hi,
First of all thanks for all your work.
I'm facing a little issue, I don't know if it's expected or not : I can't change the value of `max_execution_time` in the php configuration.
I made the change in `deployment/octane/php.ini` file, but when the container is running and I run `phpinfo()`, I see `max_execution_time` is set to 0.
When running PHP from the command line the default setting is 0. From : https://www.php.net/manual/en/info.configuration.php#ini.max-execution-time
I'm able to change other PHP configuration like `default_socket_timeout` for example.

Also a last thing, not really related to your Dockerfile : When we run an artisan command, the `boot` and `register` methods of `AppServiceProvider` are triggered. Is it excepted ?

Thanks for the help !

**Comment by smortexa** [comment]
Hi @Cemoche, for HTTP requests maximum execution time, see laravel/octane#470 and swoole/swoole-src#4594. It's not about PHP configuration or Octane as a long-running process. Currently, Swoole doesn't support limiting HTTP requests execution time in the Octane concurrency model,  but [Open Swoole does](https://openswoole.com/docs/modules/swoole-server/configuration#max_request_execution_time).

And about your question, Yes. It's excepted.

**Comment by Cemoche** [comment]
Hi @smortexa, thanks for the answer. I'll watch for the feature request you made 👍.
