### ISSUE TITLE
Local development - WARN exited: octane_00 (exit status 139; not expected)

### ISSUE THREAD

**Issue by iamvincentong** [exaco/laravel-octane-dockerfile#79]
I performed the following steps to set up my Laravel project with Docker:

1. Created a new Laravel project.
2. Navigated to the newly created Laravel project directory and installed Laravel Octane.
3. After installing Octane, cloned directory contents, including the deployment directory, Dockerfile, and .dockerignore, into the Laravel project directory.
4. In the Laravel project directory, ran the following commands:

docker build -t octane-test1:latest -f FrankenPHP.Dockerfile .

docker run -p 80:8000 --rm octane-test1:latest

I encountered the following errors (as shown in the screenshot below):
![SCR-20240519-pngd](https://github.com/exaco/laravel-octane-dockerfile/assets/92151175/7bad692c-a78d-4215-81de-08e8fce89489)

Could someone assist with troubleshooting this issue? Thank you.

**Comment by denistorresan** [comment]
Hi @iamvincentong  are you running it on Mac arm64 / v8 or similar ?

**Comment by iamvincentong** [comment]
Yes running on Mac M3 Max arm64.

**Comment by denistorresan** [comment]
I'm running the same problem on a Mac arm64 of my customer with a tested application that run perfectly on Windows and Linux.
Actually I'm unable to test it because I don't have a mac to test it, but seems there's an incompatibility based on arm platform (?!)

**Comment by smortexa** [comment]
First, these Dockerfiles are intended for production, not development. Second, this is an upstream issue. You can follow it in [dunglas/frankenphp](https://github.com/dunglas/frankenphp).

**Comment by putrafajarh** [comment]
@smortexa, if I read the issue on frankenphp its related to mlocati.
