### ISSUE TITLE
{BUG} /usr/bin/env: 'bash\r': No such file or directory

### ISSUE THREAD

**Issue by 4183r** [exaco/laravel-octane-dockerfile#8]
After building the docker image and running it. 
`docker run -p 8000:9000 --rm panja:latest`
it's giving an error
`/usr/bin/env: 'bash\r': No such file or directory`

![image](https://user-images.githubusercontent.com/39749258/152946069-62d510c9-efb0-4031-bbd4-c5f415c63ef9.png)

**Comment by 4183r** [comment]
As mentioned on another thread  https://github.com/exaco/laravel-octane-dockerfile/issues/4
I've updated ENTRYPOINT

`CMD ["/usr/bin/supervisord","-c","/etc/supervisor/conf.d/supervisord.app.conf"]`
![image](https://user-images.githubusercontent.com/39749258/152950477-0df20eda-4a70-47fc-82f9-dc0161622f34.png)

and it worked!
but for some reason. it's giving a new error 

![image](https://user-images.githubusercontent.com/39749258/152950629-4b42212c-2eb9-4096-b039-3d3600ca17cb.png)

`In StreamHandler.php line 216:
                                                                               
  There is no existing directory at "/www/wwwroot/newpanja.test/storage/logs"  
   and it could not be created: Permission denied`

**Comment by 4183r** [comment]
but the file does exist inside docker. 

![image](https://user-images.githubusercontent.com/39749258/152951814-38de94e2-e44a-4c59-b812-0d5dcd12be0b.png)

**Comment by smortexa** [comment]
Please run `ls -la` in `storage/logs` and send the output.

**Comment by 4183r** [comment]
![image](https://user-images.githubusercontent.com/39749258/152952572-1637210a-b688-4e60-b2c9-f6081bee1cdd.png)

**Comment by smortexa** [comment]
The `/usr/bin/env: 'bash\r': No such file or directory` is about OS line endings. You should remove `\r` chars. If you are using VSCode, open the `entrypoint.sh` and all other bash files and change the end of line sequence to `LF` and rebuild the image.

![eTlq9JHwiT](https://user-images.githubusercontent.com/47121888/152953334-9c705702-3e7a-4321-ac49-39625ac0fd8a.png)

**Comment by 4183r** [comment]
Thank you @smortexa that does fix the issue.

![image](https://user-images.githubusercontent.com/39749258/152956315-2bbec861-8b1a-48be-b075-37914f523352.png)

do you know why `storage/logs` it's taking the local directory of my server in instead of `/var/www/html`

**Comment by smortexa** [comment]
Did you change the `WORKDIR` in the Dockefile?

**Comment by 4183r** [comment]
![image](https://user-images.githubusercontent.com/39749258/152957357-341c7057-67de-4f90-937a-1d9cf94a2eb7.png)
![image](https://user-images.githubusercontent.com/39749258/152957378-784001bc-2cf9-4162-a721-ba861418b6d5.png)

Nope

**Comment by 4183r** [comment]
Sorry I missed `Change directory to your Laravel project`

lemme try to rebuild the image again!

**Comment by 4183r** [comment]
![image](https://user-images.githubusercontent.com/39749258/152963899-7924550d-3fda-43cd-a31c-cb182f45ce16.png)
this error is already mentioned on  https://github.com/exaco/laravel-octane-dockerfile/issues/3

**Comment by 4183r** [comment]
As you have mentioned to remove `--no-dev` from the composer. it does work but octane stopped working.
`Could not open input file: artisan`

**Comment by 4183r** [comment]
![image](https://user-images.githubusercontent.com/39749258/152966799-3ea404f5-d867-4e59-a8cf-72f02d271712.png)

**Comment by 4183r** [comment]
Thank you @smortexa it works.

i think it's best if we can pass WORKDIR via ` --build-arg`  what do you think?

**Comment by smortexa** [comment]
IMO, It's OK what is it.
