### ISSUE TITLE
FrankenPHP Logging Not Working In Google Cloud

### ISSUE THREAD

**Issue by yunus89** [exaco/laravel-octane-dockerfile#82]
We are using `FrankenPHP.Alpine.Dockerfile` in a simple laravel application that is deployed on Google Cloud Run.
Logging is needed to go to Google Cloud logging.

This is the code added to facilitate logging though is not working
In `config/logging.php` and `LOG_CHANNELS` is set to `stderr`

`'stderr' => [`
           `    'driver' => 'monolog',`
            `   'level' => env('LOG_LEVEL', 'debug'),`
           `    'handler' => StreamHandler::class,`
            `   'formatter' => env('LOG_STDERR_FORMATTER', \Monolog\Formatter\GoogleCloudLoggingFormatter::class),`
            `   'with' => [`
                `      'stream' => 'php://stderr',`
             `   ],`
   `],`

Whenever is `Log::debug(something)` the log is not written to Google Cloud Logging. What is needed for us to enable logging ?

**Comment by smortexa** [comment]
It is likely an upstream issue. Please open an issue on the Laravel Octane repository.
