### ISSUE TITLE
Laravel gRPC Server Swoole

### ISSUE THREAD

**Issue by phuongphan-discoveryloft** [exaco/laravel-octane-dockerfile#84]
Hello, I would like to thank you for this repo which is so impressive. I'm looking to learn about swole's gRPC and need some advice. Thank you!

https://openswoole.com/docs/modules/grpc-server

**Comment by smortexa** [comment]
Thank you! I’m glad to hear that you find the repository impressive.
I haven’t used gRPC in my projects so far.

**Comment by phuongphan-discoveryloft** [comment]
Hi @smortexa, I tried to build using RoadRunner, I got the error as shown in the attachment. The command I'm using is: `docker build -t phuong:ms1 -f RoadRunner.Alpine.Dockerfile .`

Could you please check what is wrong with it? thank you!!!
![image](https://github.com/user-attachments/assets/70d4becd-73a5-4694-bd78-9f3eecdcce52)

**Comment by smortexa** [comment]
Please check  [Laravel Octane and RoadRunner setup](https://laravel.com/docs/11.x/octane#roadrunner).
