### ISSUE TITLE
question about horizon

### ISSUE THREAD

**Issue by ha-family** [exaco/laravel-octane-dockerfile#85]
![image](https://github.com/user-attachments/assets/ad4f00ce-da1c-41ce-9936-7855ec43b50f)

I would like to ask about the usage of Horizon. After successfully starting the service, I saw an error message as shown in the image. The CPU usage keeps increasing, and I am not sure how to prevent it from continuously retrying.

And I am not sure why my Docker container STATUS changes to unhealthy after a while.

**Comment by smortexa** [comment]
Which container mode are you using? Is there any error log?

**Comment by ha-family** [comment]
I executed the following command: docker run -d -e WITH_SCHEDULER=true -e WITH_HORIZON=true -p 8011:8000 --name laravel_octane_cicd $TAG_LATEST

I need the scheduler functionality and want to test Horizon for handling queues, although I'm not sure if WITH_HORIZON refers to Horizon in Laravel.

**Comment by smortexa** [comment]
The command is correct. Is there any error log in Laravel log files or the container logs?

**Comment by ha-family** [comment]
I checked the logs of the Docker container, and the content is the same as shown in the image. I’m not sure if there’s a port conflict, but the octane_00 process is being frequently terminated and restarted.

Then, my CPU usage spiked to 99%, and after that, I was unable to connect via SSH. I had to stop the EC2 instance and restart it.

![image](https://github.com/user-attachments/assets/4a54a0d9-5cc4-4608-9c9b-8204a9ecb315)

![image](https://github.com/user-attachments/assets/e4b1ec40-fe9e-40b0-af24-36e3d2299797)

![image](https://github.com/user-attachments/assets/6ebd534f-77bd-44ac-b54c-3f80ff4d19a8)

**Comment by ha-family** [comment]
/storage/logs/horizon.log

![image](https://github.com/user-attachments/assets/994bfcc2-aa03-426a-9ffe-f358b451ae6e)


/storage/logs/scheduler.log
![image](https://github.com/user-attachments/assets/37acc22a-07cf-41bb-a6f4-434032e53677)

/storage/logs/laravel.log
![image](https://github.com/user-attachments/assets/1153cef2-2172-459a-a5f7-fa7acdc3861a)

/storage/logs/swoole_http.log
![image](https://github.com/user-attachments/assets/8a479cf4-f315-4102-9ca2-f1bae0eba82c)

**Comment by smortexa** [comment]
It appears that the `horizon` package has not been installed.

**Comment by ha-family** [comment]
I thought the Dockerfile had already installed Horizon for me.
And I'm simply running this Dockerfile, so there are no other services in my container. There shouldn't be a port conflict unless the scheduler is also using port 8000.
